import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/home.module.css'
import NestedLayout from "../components/nestedLayout";
import Image from "next/image";
import bottomShape from "../public/images/home-bottom-shape.png";
import AppHeaderContent from "../components/appHeader";
import homeFont from "../public/images/home-font.png";
import Card from "../components/card";
import about from "../public/images/about.jpg";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Braincase</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <header className={styles.appHeader}>
                <NestedLayout>
                    <AppHeaderContent/>
                </NestedLayout>

                <NestedLayout>
                    <div className={styles.centerDiv}>
                        <div className={styles.colLeft}>
                            <h4 className={styles.intro}>IT Läsungen & Business Leistungen Unternehmen</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                incididunt
                                ut labore et dolore magna aliqua, magna aliqua. ipsum is simply dummy text of the
                                printing.</p>
                        </div>
                        <div className={styles.colRight}>
                            <Image className={styles.Image} src={homeFont} alt="home-image"/>
                        </div>
                    </div>
                </NestedLayout>

                <div className={styles.bottomDiv}>
                    <Image src={bottomShape} height={440} alt="bottom-shape"/>
                </div>
            </header>


            <main className={styles.mainBody}>
                <NestedLayout>
                    <section className={styles.solutionContainer}>
                        <h6 className={styles.centeredSmallTitle}>Was wir anbieten</h6>
                        <h4 className={styles.centeredTitle}>IT Lösungen</h4>
                        <div className={styles.gridSystem}>
                            <Card titel="Test"/>
                            <Card titel="Docker"/>
                            <Card titel="IT"/>
                            <Card titel="Java"/>
                            <Card titel="Angular"/>
                            <Card titel="Spring"/>
                        </div>
                    </section>
                    <section className={styles.aboutContainer}>
                        <div className={styles.row}>
                            <div className={styles.col1}>
                                <h6 className={styles.smallTitle}>Über unsere Firma</h6>
                                <h4 className={styles.title}>Providing your business with a quality IT service is our
                                    passion.</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua enim ad minim veniam, nostrud</p>
                            </div>
                            <div className={styles.col2}>
                                <Image src={about} alt="about png"/>
                            </div>
                        </div>
                    </section>
                </NestedLayout>
            </main>

        </div>
    )
}

export default Home
