import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NestedLayout from "../components/nestedLayout";
import Image from "next/image";
import bottomShape from "../public/images/home-bottom-shape.png";
import AppHeaderContent from "../components/appHeader";
import homeFont from "../public/images/home-font.png";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Braincase</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <header className={styles.appHeader}>
                <NestedLayout>
                    <AppHeaderContent/>
                </NestedLayout>

                <NestedLayout>
                    <div className={styles.centerDiv}>
                        <div className={styles.colLeft}>
                            <h4 className={styles.intro}>IT Solutions & Business Services Company</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                incididunt
                                ut labore et dolore magna aliqua, magna aliqua. ipsum is simply dummy text of the
                                printing.</p>
                        </div>
                        <div className={styles.colRight}>
                            <Image className={styles.Image} src={homeFont} alt="home-image"/>
                        </div>
                    </div>
                </NestedLayout>

                <div className={styles.bottomDiv}>
                    <Image src={bottomShape} height={440} alt="bottom-shape"/>
                </div>
            </header>

            <NestedLayout>
                <main className={styles.mainBody}>
                    <p>Hello</p>
                </main>
            </NestedLayout>
        </div>
    )
}

export default Home
