import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/home.module.css'
import NestedLayout from "../components/nestedLayout";
import Image from "next/image";
import bottomShape from "../public/images/home-bottom-shape.png";
import AppHeaderContent from "../components/appHeader";
import homeFont from "../public/images/home-font.png";
import Card from "../components/card";
import about from "../public/images/about.jpg";
import { faPeopleGroup, faMobile, faStar, faAddressBook, faGear } from '@fortawesome/free-solid-svg-icons';
import albis from "../public/images/Albis-11.jpg";
import Images from '../components/images';
import raiffeisen from "../public/images/Raiffeisen-11.jpg";
import atis from "../public/images/Atis-11.jpg";
import bgPhoenix from "../public/images/BG-Phoenics-11.jpg";
import dbiso from "../public/images/DBIS0.jpg";
import dbSystel from "../public/images/DBSystel-10.jpg";
import dbvertrieb from "../public/images/DBVERTRIEB-11.jpg";
import dell from "../public/images/Dell-11.jpg";
import deutscheBank from "../public/images/DeuscheBank-1.jpg";
import deutschepost from "../public/images/Deutsche-Post-11.jpg";
import dvberatung from "../public/images/Deutsche-Vermogensberatung-2.jpg";
import grenkeLeasing from "../public/images/Grenke-Leasing-11.jpg";
import ingDiba from "../public/images/IngDiba-11.jpg";
import sanofi from "../public/images/Sanofi1-11.jpg";
import Footer from '../components/footer';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Braincase</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <header className={styles.appHeader}>
                <NestedLayout>
                    <AppHeaderContent />
                </NestedLayout>

                <NestedLayout>
                    <div className={styles.centerDiv}>
                        <div className={styles.colLeft}>
                            <h4 className={styles.intro}>IT Läsungen & Business Leistungen Unternehmen</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                incididunt
                                ut labore et dolore magna aliqua, magna aliqua. ipsum is simply dummy text of the
                                printing.</p>
                        </div>
                        <div className={styles.colRight}>
                            <Image className={styles.Image} src={homeFont} alt="home-image" />
                        </div>
                    </div>
                </NestedLayout>

                <div className={styles.bottomDiv}>
                    <Image src={bottomShape} height={440} alt="bottom-shape" />
                </div>
            </header>


            <main className={styles.mainBody}>
                <NestedLayout>
                    <section className={styles.solutionContainer}>
                        <h6 className={styles.centeredSmallTitle}>Was wir anbieten</h6>
                        <h4 className={styles.centeredTitle}>IT Lösungen</h4>
                        <div className={styles.gridSystem}>
                            <Card titel="Software Test Beratung" body="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas vero eligendi molestias" iconUrl={faPeopleGroup} />
                            <Card titel="Mobile Anwendungen" body="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas vero eligendi molestias" iconUrl={faMobile} />
                        </div>
                    </section>
                    <section className={styles.aboutContainer}>
                        <div className={styles.row}>
                            <div className={styles.col1}>
                                <h6 className={styles.smallTitle}>Über unsere Firma</h6>
                                <h4 className={styles.title}>Providing your business with a quality IT service is our
                                    passion.</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua enim ad minim veniam, nostrud</p>
                                <div>
                                    <button className={styles.customButton}>Entdecken Sie</button>
                                </div>
                            </div>
                            <div className={styles.col2}>
                                <Image src={about} alt="about png" />
                            </div>
                        </div>
                    </section>
                    <section className={styles.brainCase}>
                        <h4 className={styles.centeredSmallTitle}>
                            Unsere Erfahrung
                        </h4>
                        <h6 className={styles.centeredTitle}>
                            Der Braincase Geist
                        </h6>
                        <div className={styles.geistGrid}>
                            <Card titel="Referenzen" body="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua enim ad minim veniam, nostrud" iconUrl={faStar} />
                            <Card titel="Qualität" body="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua enim ad minim veniam, nostrud" iconUrl={faAddressBook} />
                            <Card titel="Prozesse" body="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua enim ad minim veniam, nostrud" iconUrl={faGear} />
                        </div>
                    </section>
                    <section className={styles.contactContainer}>
                        <h6 className={styles.centeredSmallTitle}>
                            Möchten Sie mit uns arbeiten?
                        </h6>
                        <h4 className={styles.centeredTitle}>
                            Eine Idee, ein Projekt, ein Bedarf Wenden Sie sich an uns!
                        </h4>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                            Ut enim ad minim veniam, quis nostrud consectetur voluptatem accusantium doloremque adipiscing elit.
                        </p>
                        <div className={styles.buttonContainer}>
                            <button className={styles.customButton}>
                                Kontaktieren Sie uns
                            </button>
                        </div>
                    </section>
                    <section className={styles.vertrauensContainer}>
                        <h6 className={styles.centeredSmallTitle}>Sie vertrauen uns</h6>
                        <h4 className={styles.centeredTitle}>Unsere Kunden</h4>
                        <div className={styles.gridImages}>
                            <Images imageSrc={albis} />
                            <Images imageSrc={raiffeisen} />
                            <Images imageSrc={atis} />
                            <Images imageSrc={bgPhoenix} />
                            <Images imageSrc={dbiso} />
                            <Images imageSrc={dbSystel} />
                            <Images imageSrc={dbvertrieb} />
                            <Images imageSrc={dell} />
                            <Images imageSrc={deutscheBank} />
                            <Images imageSrc={deutschepost} />
                            <Images imageSrc={dvberatung} />
                            <Images imageSrc={grenkeLeasing} />
                            <Images imageSrc={ingDiba} />
                            <Images imageSrc={sanofi} />
                        </div>
                    </section>
                </NestedLayout>
            </main>
            <Footer/>
        </div>
    )
}

export default Home


